# This file was generated by @liquid-labs/catalyst-builder-node. Refer to
# https://npmjs.com/package/@liquid-labs/catalyst-builder-node for further details

#####
# build dist/terminal-text.js
#####

CATALYST_TERMINAL_TEXT_JS:=$(DIST)/terminal-text.js
CATALYST_TERMINAL_TEXT_JS_ENTRY=$(SRC)/lib/index.js
BUILD_TARGETS+=$(CATALYST_TERMINAL_TEXT_JS)

$(CATALYST_TERMINAL_TEXT_JS): package.json $(CATALYST_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(CATALYST_TERMINAL_TEXT_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(CATALYST_ROLLUP) --config $(CATALYST_ROLLUP_CONFIG)

#####
# end dist/terminal-text.js
#####
